name: github_actions_gtest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: apt
      run: sudo apt-get update && sudo apt-get install sqlite3 && sudo apt-get install libsqlite3-dev
    - name: setup gnu
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install -y g++-11
    - name: make
      run: sudo make -f Mk_test
    - name: test
      run: cd bin && ./tests
